### ISSUE TITLE
Fix gulp install on heroku failing

### ISSUE THREAD

**Issue by Coteh** [Coteh/hacka-news-web#7]
At the moment, when deploying to heroku, it errors out on the semantic-ui install and the output is similar to what is depicted in this issue: https://github.com/Semantic-Org/Semantic-UI/issues/4292

In the output of the run below, I tried using a shrinkwrap to override gulp-prompt's dependency of inquirer to the newest version of 3.2.3, but it did not work. This error will also come up all the same if I use a package-lock.

```
remote: -----> Building dependencies
remote:        Installing node modules (package.json + shrinkwrap)
remote:
remote:        > semantic-ui@2.2.11 install /tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/semantic-ui
remote:        > gulp install
remote:
remote:        [04:03:22] Using gulpfile /tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/semantic-ui/gulpfile.js
remote:        [04:03:22] Starting 'install'...
remote:        [04:03:22] Starting 'run setup'...
remote:        25l? Set-up Semantic UI (Use arrow keys)
remote:        ❯ Automatic (Use default locations and all components)
remote:        Express (Set components and output folder)
remote:        Custom (Customize all src/dist values) [04:03:22] 'run setup' errored after 39 ms
remote:        [04:03:22] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
remote:        at new RegExp (<anonymous>)
remote:        at breakLines (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
remote:        at module.exports.ScreenManager.render (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
remote:        at Prompt.render (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/prompts/list.js:103:15)
remote:        at Prompt._run (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/prompts/list.js:74:8)
remote:        at Prompt.run (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/prompts/base.js:57:8)
remote:        at Object.<anonymous> (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/ui/prompt.js:84:12)
remote:        at module.exports (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/run-async/index.js:15:21)
remote:        at AnonymousObservable.__subscribe (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/utils/utils.js:16:7)
remote:        at AnonymousObservable.tryCatcher (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/rx-lite/rx.lite.js:63:31)
remote:        [04:03:22] 'install' errored after 44 ms
remote:        [04:03:22] SyntaxError in plugin 'run-sequence(run setup)'
remote:        Message:
remote:        Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
remote:        Stack:
remote:        SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
remote:        at new RegExp (<anonymous>)
remote:        at breakLines (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
remote:        at module.exports.ScreenManager.render (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
remote:        at Prompt.render (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/prompts/list.js:103:15)
remote:        at Prompt._run (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/prompts/list.js:74:8)
remote:        at Prompt.run (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/prompts/base.js:57:8)
remote:        at Object.<anonymous> (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/ui/prompt.js:84:12)
remote:        at module.exports (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/run-async/index.js:15:21)
remote:        at AnonymousObservable.__subscribe (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/inquirer/lib/utils/utils.js:16:7)
remote:        at AnonymousObservable.tryCatcher (/tmp/build_32d85e6c5ff35acee9556d5f57715041/node_modules/rx-lite/rx.lite.js:63:31)
```

**Comment by Coteh** [comment]
Got it deployed to Heroku using Docker image so going to close this.
